// app/layout.js

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";

import { AppointmentProvider } from "@/context/SetContext";
import { TourProvider } from "@/context/TourContext";
import TourOverlay from "@/components/TourOverlay/TourOverlay";
import BootstrapClientLoader from "@/components/BootstrapClientLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ERP4Dentist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* ✅ Bootstrap JS loaded client-side */}
        <BootstrapClientLoader />

        <AppointmentProvider>
          <TourProvider>
            <TourOverlay />
            {children}
          </TourProvider>
        </AppointmentProvider>
      </body>
    </html>
  );
}
